= CalConnect Standard: Streaming Calendar and Contacts Data

This work item belongs to CalConnect CALENDAR TC.

image:https://github.com/CalConnect/cc-streaming-cal-contacts-data/workflows/generate/badge.svg["Build Status", link="https://github.com/CalConnect/cc-streaming-cal-contacts-data/actions?workflow=generate"]

This document is available in its rendered forms here:

* https://calconnect.github.io/cc-streaming-cal-contacts-data/[CalConnect: Streaming Calendar and Contacts Data (HTML)]

== General

This document specifies a model for streaming calendar and contact data. This allows for a more efficient method for synchronizing collections of data and may be used to augment existing protocols such as CalDAV.

The document is published as the following:

* CalConnect CC 51016
* IETF draft-douglass-streaming-cal-contacts-data


== Fetching the document

[source,sh]
----
git clone https://github.com/CalConnect/cc-streaming-cal-contacts-data/
----


== Installing build tools

See https://www.metanorma.com/author/topics/install/


== Running via Docker or locally

If you have installed the build tools locally, and wish to run the
locally-installed compilation tools, there is nothing further to set.

If you don't want to deal with local dependencies, use the docker:

[source,sh]
----
docker run -v "$(pwd)":/metanorma -w /metanorma -it metanorma/mn metanorma site generate --agree-to-terms
----


== Building the document

[source,sh]
----
metanorma site generate --agree-to-terms
----

The generated documents are accessible under `_site/`.


== Iterating the document

[source,sh]
----
metanorma site generate --agree-to-terms
open _site/index.html
----


== License

Copyright its respective authors and CalConnect.
