[[connections]]
== Connections

=== Introduction

This specification assumes that there are two virtual streams open for each
established virtual connection: an output stream and an input stream.

All operations are carried out by either end writing a message on the output stream
and receiving an acknowledgment on the input stream.

All messages MUST receive an acknowledgement within the defined timeout period or
they or their acknowledgement will be assumed to have been lost. The sender will
need to carry out any appropriate recovery.

Each message sent MUST include a unique (within the connection) identifier which
will be returned in the acknowledgment.

=== Virtual Connections

The actual systems on which this is running may have many restrictions. Connections
may be forcibly shut down after some idle time and there will be the usual issues
with mobile devices and connectivity.

The virtual connection MUST hide these issues from the client. A connection will
last until one end is deemed to have shut down the connection.

On subsequent conditional fetches the entity will not be returned.

=== Examples

[example]
====
This is an example of the initial request and response from a server that supports
the extended GET protocol.

[source%unnumbered]
----
>> Request <<

GET /events.ics HTTP/1.1
Host: example.com
Accept: text/calendar

>> Response <<

HTTP/1.1 200 OK
Content-Length: xxxx
ETag: "1234"                    current ETag (for conditional GET)
Vary: Prefer, If-None-Match            so caching proxy can key off of client's ETag (sync token) and preference
 
BEGIN:VCALENDAR:
...  /* full feed */
END:VCALENDAR
----
====

[example]
====
This is an example of the subsequent request and response when no changes have
occurred. The Accept header field indicates that a VPATCH format is most desirable
but simple text/calendar is acceptable.

[source%unnumbered]
----
>> Request <<

GET /events.ics HTTP/1.1
Host: example.com
Accept: text/calendar; q=0.5, component=VPATCH, text/calendar;
If-None-Match: "1234"            conditional request
Prefer: return=minimal

>> Response <<

HTTP/1.1 304 Not Modified
Content-Length: 0
ETag: "1234"
Vary: Prefer, If-None-Match
----
====

[example]
====
This is an example of the subsequent request and response when changes have occurred
and the server can create the minimal format.

[source%unnumbered]
----
>> Request <<

GET /events.ics HTTP/1.1
Host: example.com
Accept: text/calendar; q=0.5, component=VPATCH, text/calendar;
If-None-Match: "1234"            conditional request
Prefer: return=minimal

>> Response <<

HTTP/1.1 200 OK
Content-Type: text/calendar
Content-Length: xxxx
ETag: "5678"                    current ETag (for conditional GET)
Preference-Applied: return=minimal    signals to client that stream is changes only
Vary: Prefer, If-None-Match            so caching proxy can key off of client's ETag (sync token) and preference

BEGIN:VCALENDAR:
...  only new/changed events
...  when not returning VPATCH, deleted events have STATUS:DELETED
END:VCALENDAR
----
====

[example]
====
This is an example of the subsequent request and response when changes have occurred
and the server cannot create the minimal format - perhaps because of an old or
invalid token. Note there is no Preference-Applied header field.

[source%unnumbered]
----
>> Request <<

GET /events.ics HTTP/1.1
Host: example.com
Accept: text/calendar; q=0.5, component=VPATCH, text/calendar;
If-None-Match: "1234"            conditional request
Prefer: return=minimal

>> Response <<

HTTP/1.1 200 OK
Content-Type: text/calendar
Content-Length: xxxx
ETag: "5678"                    current ETag (for conditional GET)
Vary: Prefer, If-None-Match            so caching proxy can key off of client's ETag (sync token) and preference

BEGIN:VCALENDAR:
...  full set of data
END:VCALENDAR
----
====
